addReviewers: true
addAssignees: author
reviewers:
<<<<<<< HEAD
  - ta543
=======
  - kamil-nowocin
  - Dominik4804C
  - krishpavuluri
  - amit-circle-k
  - tandersonqa
  - tosgu
  - pdongare27
  - ShrutiCircleK
  - yashaswini-circle-k
  - hareshprajapati11
  - pankaj-circle-k
  - Abhijit-Circle-K
  - Santhosh-Circle-K
>>>>>>> 123b506b8a72c0fa96073a8b882d639a13550deb
numberOfReviewers: 0
filterLabels:
  exclude:
    - build-failure
