name: VeriFlow | Compile

permissions:
  contents: write
  pull-requests: write
  issues: write

  #

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: false

run-name: '👷🚧[#${{ github.run_number }}][VeriFlow] PR: "${{ github.event.pull_request.title }}"'

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: "Compile 🛠️"

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4

      - name: "Set up Elixir"
        uses: erlef/setup-elixir@v1
        with:
          otp-version: "25.0"
          elixir-version: "1.14.0"

      - name: "Cache Mix dependencies"
        uses: actions/cache@v4
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix

      - name: "Install Dependencies"
        id: install_dependencies
        run: mix deps.get

      - name: "Set Compile Result"
        if: always()
        run: |
          if [[ "${{ steps.install_dependencies.outcome }}" == "failure" ]]; then
            echo "compile_result=failure" >> $GITHUB_ENV
            exit 1
          else
            echo "compile_result=success" >> $GITHUB_ENV
          fi

      - name: "Apply Labels"
        if: github.event_name == 'pull_request' && github.actor != 'dependabot[bot]' && always()
        uses: actions/github-script@v7
        env:
          compile_result: ${{ env.compile_result }}
        with:
          script: |
            const labels = [
              { name: 'build-success', color: '0E8A16', description: 'Build succeeded' },
              { name: 'build-failure', color: 'B60205', description: 'Build failed' }
            ];

            const resultLabelCompile = process.env.compile_result === 'success' ? 'build-success' : 'build-failure';

            async function manageLabels(github, context, labels, compileResultLabel) {
              const issue_number = context.payload.pull_request.number;
              const { owner, repo } = context.repo;

              for (const label of labels) {
                try {
                  await github.rest.issues.updateLabel({
                    owner,
                    repo,
                    name: label.name,
                    color: label.color,
                    description: label.description
                  });
                } catch (error) {
                  if (error.status === 404) {
                    await github.rest.issues.createLabel({
                      owner,
                      repo,
                      name: label.name,
                      color: label.color,
                      description: label.description
                    });
                  }
                }
              }

              await github.rest.issues.addLabels({
                owner,
                repo,
                issue_number,
                labels: [compileResultLabel] // Ensure this is an array
              });
            }

            manageLabels(github, context, labels, resultLabelCompile);

      - name: "Post Comment on PR"
        if: github.event_name == 'pull_request' && github.actor != 'dependabot[bot]' && always()
        uses: actions/github-script@v7
        with:
          script: |
            const url = `${process.env.GITHUB_SERVER_URL}/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`;
            const compileMessage = process.env.compile_result === 'success'
              ? '✅ Compilation completed successfully.'
              : `❌ Compilation failed. [View Workflow Run](${url})`;

            const testMessage = ''; // Ensure this variable is defined
            const message = `${compileMessage}\n${testMessage}`;

            github.rest.issues.createComment({
              issue_number: context.payload.pull_request.number,  // Corrected reference
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: message
            });
