name: VeriFlow | Validate PR

run-name: "👷🚧[#${{ github.run_number }}][Validate PR] Name: \"${{ github.event.pull_request.title }}\""

on:
  pull_request:
    types: [opened, ready_for_review, reopened, synchronize]

permissions:
  pull-requests: write
  issues: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: "Validate PR🔖"
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4

      - name: "Auto Assign PR"
        uses: kentaro-m/auto-assign-action@v2.0.0

      - name: "Get PR Author"
        id: pr_author
        run: echo "::set-output name=author::$(jq --raw-output .pull_request.user.login $GITHUB_EVENT_PATH)"

      - name: "Assign label based on author"
        uses: actions/github-script@v7
        with:
          script: |
            const author = '${{ steps.pr_author.outputs.author }}';
            let label = '';

            const chappy = ['ta543'];

            if (chappy.includes(author)) {
              label = 'chappy';
            }

            if (label) {
              const issue_number = context.issue.number;
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number,
                labels: [label],
              });
            }

      - name: "Set up Node.js"
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: "Cache Node.js dependencies"
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-

      - name: "Install dependencies"
        run: npm ci
